version: '3'
services:
  app:
    container_name: app
    build: ./app
    ports:
      - '8080:8080'
    environment:
      - production=1
    links:
      - mongo
      - neo4j
  mongo:
    container_name: mongo_server
    image: mongo
    volumes :  
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
  neo4j:
    container_name: neo4j_server
    image: neo4j:3.5.6
    environment: 
      - NEO4J_AUTH=neo4j/secret
    volumes:
      - ./data/neo:/data/databases/graph.db
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"